# Generated by Django 4.1.3 on 2022-11-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_follow_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
