# Generated by Django 4.1.3 on 2022-11-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_currency_base_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.currency'),
        ),
    ]
