# Generated by Django 4.1.3 on 2022-11-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_currency_base_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.basecurrency'),
        ),
    ]
