# Generated by Django 4.1.3 on 2022-11-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_item_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, default='https://apply.sts.net.pk/assets/images/default-upload-image.jpg'),
        ),
    ]
