# Generated by Django 4.1.3 on 2022-11-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_bidder_alter_comment_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
